### ISSUE TITLE
can't ping with socks proxy

### ISSUE THREAD

**Issue by ahxxm** [chengr28/DNSPing#2]
![image](https://cloud.githubusercontent.com/assets/1286225/13194630/0b8965d2-d7d3-11e5-94e3-89876a571508.png)

System: OS X

**Comment by chengr28** [comment]
OS X 版本的确有问题……之前都没有留意到，似乎是因为 OS X 系统对 API 要求比较严格造成的，Windows 和 Linux 那边都没有问题。刚才更新了 0.2.1.0 已经修复这个问题了w
