### ISSUE TITLE
win10x64 could not start DNSPing.exe

### ISSUE THREAD

**Issue by KiritoStudio** [chengr28/DNSPing#4]
![image](https://cloud.githubusercontent.com/assets/553215/14746415/20467114-08e2-11e6-9d3f-178c08762cd9.png)

**Comment by chengr28** [comment]
不好意思最近比较忙，现在才看到……
请问是通过 GitHub 的 Download ZIP 功能下载回去的吗？如果直接 git 出来，不知道是不是对换行符之类的格式处理有问题，出来的可执行程序是有可能出现这种情况的。刚才测试过，Download ZIP 回来的并没有问题

**Comment by wongsyrone** [comment]
看起来被识别成16位程序了，估计是PE文件结构坏掉了
